version: '3'
services:
  nginx:
    container_name: web-server
    image: nginx:1.13
    restart: always
    ports:
      - 8088:80
      - 4443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
  app:
    restart: always
    #image: maven:ibmjava-alpine
    #image: maven:3.5-jdk-8
    image: maven:3.6.3-jdk-11-openj9
    working_dir: /app
    volumes:
      - ./:/app
      - ./src/main/resources/application.properties.local:/app/src/main/resources/application.properties
    expose:
      - "8080"
    command: mvn clean spring-boot:run
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=
      - POSTGRES_USER=postgres
      - POSTGRES_DB=ecommerce
